# -*- coding: utf-8 -*-
"""210818_aed_anotacoes_thiagoaraujo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZLZ80yQMcKvn_oWiM70X-_Vo1edfC9bm
"""

import pandas as pd

dados = pd.read_csv('gapminder_data.csv')

dados

dados.info()

"""#Estatísticas descritivas"""

dados.describe()

"""#Buscando o Brasil"""

dados.query("country == 'Brazil'")

"""#Qual é a expectativa de vida média (por ano), em cada continente?"""

dados.groupby([ 'continent', 'year']).agg({'lifeExp':[ 'mean','max'], 'gdpPercap':'median'})

"""#Brasil"""

brasil = dados.query("country=='Brazil'")

brasil.plot('year', 'gdpPercap')