# -*- coding: utf-8 -*-
"""210929_aed_trabalhofinal_anotacoes_perguntas_thiagoaraujo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17JWx76umi572MpvDXS6CFhDhiJdgdkVo
"""

import pandas as pd

lgbt_casamento = pd.read_csv('https://raw.githubusercontent.com/gabrielacaesar/lgbt_casamento/main/data/lgbt_casamento.csv')

"""# Considerando todos os anos, em que estados aconteceram mais casamentos LGBTs em números absolutos? """

lgbt_casamento.groupby('uf')['numero'].sum().sort_values(ascending=False)

"""# Considerando todos os anos, em que estados aconteceram MENOS casamentos LGBTs em números absolutos? """

lgbt_casamento.groupby('uf')['numero'].sum().sort_values(ascending=True)