# -*- coding: utf-8 -*-
"""210813_penscompu_aula2_anotacoes_censo_thiagoaraujo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BMb3it7RJDfDFwDdJP4jv_l2gtx4ccPP
"""

print("Censo 2021, estilo faça-você-mesmo:")
nome = input("Qual seu nome? ")
ano_nascimento = int(input("Em que ano você nasceu? ")) #int é a função para converter texto em número

print("Sua idade deve ser:")
print(2021 - ano_nascimento) #É possível converter aqui o texto em número, mas a boa prática

print(type("Olá, mundo!"))      # str -> string, texto
print(type("Aspas duplas"))     # string também! Está entre aspas simples
print(type('Aspas simples'))    # string de novo! Tanto faz se simples ou duplas
print(type(42))                 # int -> integer, número inteiro
print(type(3.14))               # float -> floating point number, número com casas decimais. Usar . e não , como separador
print(type(3 + 4j))             # complex -> número complexo (parte real e imaginária)
print(type(3 > 4))              # bool -> "booleano", verdadeiro/falso

altura = float(input("Digite sua altura: "))
print(altura - 1)

print("Censo 2021, estilo faça-você-mesmo:")
nome = input("Qual seu nome? ")
ano_nascimento = int(input("Em que ano você nasceu? ")) #int é a função para converter texto em número
possivel_idade = 2021 - ano_nascimento
print("Thiago deve ter " + str(possivel_idade) + " anos.")

print(f"{nome} deve ter {possivel_idade} anos, pois nasceu em {ano_nascimento}.")

numero_1 = int(input("Qual o primeiro número? "))
numero_2 = int(input("Qual o segundo número? "))
media = (numero_1 + numero_2) / 2
print(f"A média da soma de {numero_1} com {numero_2} é {media}")

if media >= 6:
  print("Maior que 6 :)")
  print(f"A média da soma de {numero_1} com {numero_2} é {media}.")
else:
  print("Menor que 6 :(")
  print(f"A média da soma de {numero_1} com {numero_2} é {media}.")

if media < 5:
  print("Média menor que 5! :(")
elif media < 6:
  print("Média menor que 6, mas maior que 5. :S")
elif media == 6:
  print("Média exatamente 6. :|)")
else:
  print("Média maior que 6! :)")