# -*- coding: utf-8 -*-
"""2100806_penscomp_anotacoes_helloworld_thiagoaraujo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dSWb0ny4h6On5C2VbcvGBF56lGOZaPQD
"""

print("Olá, mundo!")

print("Estou aprendendo Python! Oba!")

"""A instrução acima mostra um texto na tela"""

nome = input("Qual seu nome? ")
print("Olá, " + nome)