# -*- coding: utf-8 -*-
"""210917_penscomp_aula7_anotacoes_sqlite_thiagoaraujo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sabhgGrdLwADh-iazAFV2R8jNoIW2Oht
"""

import sqlite3 

db = sqlite3.connect("brasil.sqlite3")

def dens():
  estado = input("Digite o estado: ")
  cursor = db.cursor()
  sql = f"""
  SELECT
    municipio,
    habitantes / area AS densidade
  FROM municipio
  WHERE
    estado = ?
    AND habitantes >= 100000
  ORDER BY
    densidade DESC
  """
  cursor.execute(sql, [estado])
  ranking = 1
  for registro in cursor.fetchall():
    municipio, densidade = registro
    print(f"O município {municipio} possui densidade de {densidade:.2f} hab/km².")
    ranking += 1

dens()