# -*- coding: utf-8 -*-
"""210827-aula3-penscomp-anotacoes-thiagoaraujo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_9shbbvH1cIHfD63sF1MFaDfpDMfPwiY
"""

import csv
bcsv = csv.DictReader(open("brasil.csv"))
for registro in bcsv:
  dens = int(registro["habitantes"]) / float(registro["area"])
  if dens > 1000:
    print(f"O município {registro['municipio']}/{registro['estado']} possui uma densidade demográfica de {dens:.0f} h/km²")