# -*- coding: utf-8 -*-
"""210827-penscomp-aula3-exerciciosolinks-thiagoaraujo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aGCsK999JN0gPAAVy-LfKFj5dHkO_gPa
"""

chat1 = open("chat1.txt") #Abre o arquivo e o define como uma variável chatN, onde N é número do chat em questão
chat2 = open("chat2.txt")
chat3 = open("chat3.txt")
chat4 = open("chat4.txt")
chat5 = open("chat5.txt")
chat6 = open("chat6.txt")
chat7 = open("chat7.txt")
chat8 = open("chat8.txt")
chat9 = open("chat9.txt")
chat10 = open("chat10.txt")
chat11 = open("chat11.txt")
chat12 = open("chat12.txt")
chat13 = open("chat13.txt")
chat14 = open("chat14.txt")

for linha in chat1: # Criação da lista para chatN
  limpo = linha.strip().split("\t") # Retira os espaços e divide os elementos
  if "http" in limpo[-1]: # Função condicional que caça-link no último elemento...
    	print(limpo[-1]) # ... e o exibe se for verdadeiro

for linha in chat2:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])
     
for linha in chat3:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])
     
for linha in chat4:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])

for linha in chat5:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])

for linha in chat6:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])

for linha in chat7:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])

for linha in chat8:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])

for linha in chat9:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])

for linha in chat10:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])

for linha in chat11:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])

for linha in chat12:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])

for linha in chat13:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])

for linha in chat14:
  limpo = linha.strip().split("\t")
  if "http" in limpo[-1]:
    	print(limpo[-1])