# -*- coding: utf-8 -*-
"""210820_penscomp_trabalho_gabischirleitode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19nWo0tFqwcvOoPwYUTq52OBC5vTuOsi5
"""

pontuacao = 0
print("Olá, vamos ver se você está ligado na pandemia!")
print(f"Pergunta 1:\n Quantas vacinas estão em uso no Brasil? \n a) 3 vacinas \n b) 2 vacinas \n c) 1 vacina \n d) Nenhuma das alternativas anteriores")
pergunta_1 = input(f"Qual a alternativa correta? \n Digite a letra ")
if pergunta_1 == "a": 
  pontuacao = pontuacao + 1
  print("Parabéns, você está antenado!")
elif pergunta_1 == "b":
  pergunta_1 = input(f"Quase lá.  Então, selecione a letra: \n a) 3 vacinas ou c) 1 vacina? ")
  if pergunta_1 == "a": 
    pontuacao = pontuacao + 1
    print("Agora sim!")
  else:
    print("Errou. Próxima pergunta!")
else:
  print("Errou. Acompanhe mais o noticiário. A resposta correta é a letra a. ")

print("Pergunta_2: Se uma pessoa já se contaminou com a Covid-19, ela pode se vacinar?")
print(" a) sim, pode tomar a qualquer momento")
print(" b) não, você pode morrer por causa disso")
print(" c) sim, porém deve aguardar a melhora dos sintomas")
print(" d) não, você corre o risco de virar jacaré ")
pergunta_2 = input("Qual a alternativa correta? Digite a letra ")
if pergunta_2 == "c": 
  pontuacao = pontuacao + 1
  print("Parabéns, você não virou jacaré!")
else:
  print("Errou. Acompanhe mais o noticiário. A resposta correta é a letra c. ")

print("Pergunta_3: Qual das alternativas é uma boa prática durante a pandemia?")
print(" a) usar a máscara pendurada no queixo")
print(" b) aglomerar com a galera")
print(" c) apertar a mão do coleguinha")
print(" d) usar a máscara cobrindo o nariz e a boca sem tirá-la ao falar ")
pergunta_3 = input("Qual a alternativa correta? Digite a letra ")
if pergunta_3 == "d": 
  pontuacao = pontuacao + 1
  print("Parabéns, você não é bolsominion")
else:
  print("Errou. Acompanhe mais o noticiário. A resposta correta é a letra d. ")

print("Pergunta_4: Em qual país foi detectado o primeiro caso de coronavírus?")
print(" a) Brasil ")
print(" b) China ")
print(" c) Itália ")
print(" d) Afeganistão ")
pergunta_4 = input("Qual a alternativa correta? Digite a letra ")
if pergunta_4 == "b": 
  pontuacao = pontuacao + 1
  print("Parabéns, você ganhou uma estrelinha!")
else:
  print("Errou. Acompanhe mais o noticiário. A resposta correta é a letra b. ")

print("Pergunta_5: Qual foi o presidente que mais passou vergonha na pandemia?")
print(" a) Bolsonaro ")
print(" b) Biden ")
print(" c) Macron ")
print(" d) Fernandez ")
pergunta_5 = input("Qual a alternativa correta? Digite a letra ")
if pergunta_5 == "a": 
  pontuacao = pontuacao + 1
  print("Parabéns, pelo menos você não passou vergonha com a resposta!")
else:
  print("Tente novamente. Não foi dessa vez! ")

print(f"Nota = {pontuacao}")
if pontuacao >= 5:
  print("Arrasou, você está muito bem informado!")
elif pontuacao == 4:
  print("Parabéns, continue assim!")
elif pontuacao == 3:
  print("Você foi bem, mas precisa estudar mais!")
else:
  print("Você está desinformado, precisa estudar mais!")