# -*- coding: utf-8 -*-
"""210924_penscomp_exercicio_funcoes_thiagoaraujo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QgHmy1CEIb0MAwvUw1JXo7o_xjBV7KaS
"""

def pedirnome():
  nome = input("Qual o seu nome? ")
  print(f"Você se chama {nome}.")

def pediridade():
  idade = input("Qual sua idade? ")
  print(f"Você tem {idade} anos.")

def nomeidade():
  pedirnome();
  pediridade();
  print(f"Você se chama {nome} e tem {idade} anos.")

nomeidade()