# -*- coding: utf-8 -*-
"""210910_penscomp_aula5_anotacoes_baixarhtml_thiagoaraujo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1657ePxUbWVJiEqlCJvk73r7h_qq0VZ4Q
"""

from urllib.request import urlopen

url = "https://pt.wikipedia.org/wiki/Jogo_eletr%C3%B4nico"
resposta = urlopen(url)
html = resposta.read().decode("utf-8")

!pip install requests

import requests

url = "https://pt.wikipedia.org/wiki/Jogo_eletr%C3%B4nico"
resposta = requests.get(url)
html = resposta.text

print(html)

import requests

pagina = "https://pt.wikipedia.org/api/rest_v1/page/summary/Counter-Strike"
baixar = requests.get(pagina)
dados = baixar.json()
print(dados["extract"])

import requests

def verbete(palavrachave):
  pagina = "https://pt.wikipedia.org/api/rest_v1/page/summary/" + palavrachave
  baixar = requests.get(pagina)
  dados = baixar.json()
  print(dados["extract"])

verbete("Microsoft")
verbete("Sprite")